### ISSUE TITLE
Add monitoring for Tiugo related stuff

### ISSUE THREAD

**Issue by dpawlowski-cksource** [cksource/tiugo-monitoring#17]
## **Why**

This is to prevent cases when products related to the `Tiugo` brand (like https://www.tiugotech.com/) are not working.

## **What**

```[tasklist]
### Tasks
- [x] Add `Ping` test for `https://www.tiugotech.com` which tests response status code and piece of content
- [x] Create a new test for Certificate expiration (save in metrics times remaining to cert expiration) and add a new Chart/Gauge/Component that displays the remaining time
- [x] Create a new test for Domain expiration (save in metrics times remaining to cert expiration) and add a new Chart/Gauge/Component that displays the remaining time
- [x] Add new label `brand/organization` to metrics to make it easier to divide into Grafana dashboards (CKSource, Tiugio, Butter, etc.)
- [x] Create a new `Tiugo` dashboard in our internal Grafana and charts for `https://www.tiugotech.com` tests
- [x] Add an alert for Certificate expiration tests (send a notification once a day when 7 days remain to expiration)
- [x] Add an alert for Domain expiration tests (send a notification once a day when 7 days remain to expiration)
- [x] Add the ability to run tests in different intervals (there is no sense in running Certificate or Domain expiration tests every 5 min...)
- [x] Configure Slack templates of alerts - they should be displayed more nicely
- [ ] Create [default Slack channels](https://www.notion.so/Alerting-flow-dda84ab3fa08412f979eaa0e5b2c0fc4?pvs=4#0ffbb9a6723280d696b8f28294b3e1d2) per organization
- [ ] Configure Grafana integration for redirecting alerts to appropriate Slack channels
```

## **When (optional)**

ASAP

**Comment by bczerwonka-cksource** [comment]
Can we just include CKS/CKE domains too? :pray: I know that we have this PR [https://github.com/cksource/cksource-monitoring/pull/16/files](https://github.com/cksource/cksource-monitoring/pull/16/files) but I'm talking here about only domains :)

**Comment by vokiel** [comment]
And others we have as well https://github.com/cksource/cs/issues/19797#issuecomment-2297242615

**Comment by dpawlowski-cksource** [comment]
> Can we just include CKS/CKE domains too? 🙏 I know that we have this PR https://github.com/cksource/cksource-monitoring/pull/16/files but I'm talking here about only domains :)

I think we could cover these 4 domains we currently have in tests
```
	new PingSiteTest( 'https://ckeditor.com/' ),
	new PingSiteTest( 'https://cksource.com/' ),
	new PingSiteTest( 'https://onlinehtmleditor.dev/' ),
	new PingSiteTest( 'https://onlinemarkdowneditor.dev/' )
```

> And other domains we have as well https://github.com/cksource/cs/issues/19797#issuecomment-2297242615

I'll add this list to this: https://github.com/cksource/cksource-monitoring/issues/15 issue and we can do it in separate PR

**Comment by LukaszGudel** [comment]
Most of the tasks from this issue are already done. The last tasks related to alerts redirecting were moved to another issue: https://github.com/cksource/tiugo-monitoring/issues/38
