### ISSUE TITLE
Remove internal Grafana

### ISSUE THREAD

**Issue by dpawlowski-cksource** [cksource/tiugo-monitoring#32]
## **Why**

Because we are using Grafana Cloud for dashboards and alerts and currently we have it duplicated.

## **What**

```[tasklist]
### Tasks
- [x] Destroy internal Grafana in AWS
- [x] Remove deploy scripts from cs-repo
- [x] Keep the ability to launch Grafana locally for development/testing purposes
- [ ] Describe/prepare flow for delivering new changes to Grafana Cloud
- [ ] (idea) Some scripts for creating configuration backup (for Cloud) and checking diffs
```

**Comment by LukaszGudel** [comment]
Grafana is removed.

Tasks related to integration with Grafana Cloud were moved to a new issue: https://github.com/cksource/tiugo-monitoring/issues/36
