### ISSUE TITLE
Introduce a flow for delivering new changes to Grafana Cloud

### ISSUE THREAD

**Issue by LukaszGudel** [cksource/tiugo-monitoring#36]
All the dashboards and alerts defined in Grafana Cloud are set up manually in the Grafana Cloud UI. It would be great to have some way for tracking the changes to dashboards and alerts, like terraform, yamls or sync scripts.

```[tasklist]
### Tasks
- [ ] Describe/prepare flow for delivering new changes to Grafana Cloud
- [ ] Integrate this flow with local Grafana during local development
- [ ] (idea) Some scripts for creating configuration backup (for Cloud) and checking diffs
```
